import os

TELEGRAM_TOKEN = "8725268285:AAE9CWjT7A9m9_mzUab8FMPmvQ0rEcLyVCE"
TELEGRAM_CHAT_ID = "6514698452"

TOP_SYMBOLS = [
    "BTC_USDT", "ETH_USDT", "SOL_USDT", "BNB_USDT",
    "XRP_USDT", "DOGE_USDT", "ADA_USDT", "AVAX_USDT",
    "LINK_USDT", "DOT_USDT", "MATIC_USDT", "UNI_USDT",
    "ATOM_USDT", "LTC_USDT", "BCH_USDT", "FIL_USDT",
    "NEAR_USDT", "APT_USDT", "ARB_USDT", "OP_USDT",
    "SUI_USDT", "INJ_USDT", "TIA_USDT", "SEI_USDT",
    "WIF_USDT", "PEPE_USDT", "SHIB_USDT", "FTM_USDT",
    "AAVE_USDT", "MKR_USDT"
]

MIN_SIGNAL_STRENGTH = 3
VOLUME_MULTIPLIER = 1.5
RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 65
EMA_FAST = 21
EMA_SLOW = 55
RISK_REWARD_1 = 2.0
RISK_REWARD_2 = 3.0
ATR_PERIOD = 14
ATR_STOP_MULTIPLIER = 1.5
